services:
  postgres:
    image: postgres:15-alpine
    container_name: tailorshop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tailorshop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres -d tailorshop_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: tailorshop_api
    depends_on:
      postgres:
        condition: service_healthy 
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_NAME: tailorshop_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data: