version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tailorshop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tailorshop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres -d tailorshop_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend

  backend:
    build: ./backend
    container_name: tailorshop_api
    depends_on:
      postgres:
        condition: service_healthy 
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_NAME: tailorshop_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL_DATABASE: tailorshop_db
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
