import { Component, Output, EventEmitter, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, FormArray, Validators } from '@angular/forms';
import { FabricService } from '../../../../../core/services/fabrics/fabric.service';
import { Fabric } from '../../../../../core/models/fabric.model';

// Assuming your Garment model (src/app/core/models/garment.model.ts)
// should now include the 'measures' field.
// Make sure this interface matches your actual model file.
export interface Garment {
    garment_id?: number; // Optional as it might be generated by backend
    order_id?: number; // Optional as it might be set later
    garment_type_id: number;
    fabric_id: number;
    quantity: number;
    person_name: string;
    details?: string;
    img?: string;
    measures: string; // The new field for detailed measures
}

@Component({
    selector: 'app-step3-garments',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule],
    templateUrl: './step3-garments.component.html',
    styleUrls: ['./step3-garments.component.scss']
})
export class Step3GarmentsComponent implements OnInit {
    // Emitting an array of Garment objects directly
    @Output() garmentsDataValid = new EventEmitter<Garment[] | null>();

    garmentsForm: FormGroup;
    fabrics: Fabric[] = [];
    garmentTypes = [
        { name: "Pantalón" },
        { name: "Chaqueta" },
        { name: "Chaleco" },
        { name: "Camisa" },
        { name: "Traje completo sin chaleco" },
        { name: "Traje completo con chaleco" }
    ];

    constructor(
        private fb: FormBuilder,
        private fabricService: FabricService
    ) {
        this.garmentsForm = this.fb.group({
            garments: this.fb.array([])
        });

        // Subscribe to value changes to emit data whenever the form updates
        this.garmentsForm.valueChanges.subscribe(() => {
            this.emitGarmentsData();
        });
    }

    ngOnInit() {
        this.loadFabrics();
        this.addGarment(); // Add an initial garment form group
    }

    // Getter for easy access to the garments FormArray
    get garmentsArray(): FormArray {
        return this.garmentsForm.get('garments') as FormArray;
    }

    // Fetches fabric data from the service
    loadFabrics() {
        this.fabricService.getFabrics().subscribe({
            next: (fabrics) => {
                this.fabrics = fabrics;
            },
            error: (error) => {
                console.error('Error loading fabrics:', error);
            }
        });
    }

    // Creates a new FormGroup for a single garment
    createGarmentFormGroup(): FormGroup {
        return this.fb.group({
            garment_type_id: ['', Validators.required],
            fabric_id: ['', Validators.required],
            quantity: [1, [Validators.required, Validators.min(1)]],
            person_name: ['', Validators.required],
            details: [''],
            img: [''],
            measures: ['', Validators.required] // The new field 'measures'
        });
    }

    // Adds a new garment form group to the FormArray
    addGarment() {
        const newGarment = this.createGarmentFormGroup();
        // Subscribe to individual garment form changes to ensure immediate emission
        newGarment.valueChanges.subscribe(() => {
            this.emitGarmentsData();
        });
        this.garmentsArray.push(newGarment);
        this.emitGarmentsData(); // Emit data after adding a new garment
    }

    // Removes a garment form group from the FormArray
    removeGarment(index: number) {
        if (this.garmentsArray.length > 1) {
            this.garmentsArray.removeAt(index);
            this.emitGarmentsData(); // Emit data after removing a garment
        }
    }

    // Handles image selection and converts it to a Data URL for preview
    onImageSelected(event: any, index: number) {
        const file = event.target.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = (e: any) => {
                this.garmentsArray.at(index).get('img')?.setValue(e.target.result);
            };
            reader.readAsDataURL(file);
        }
    }

    // Helper to get garment type name from its ID
    getGarmentTypeName(typeId: number): string {
        if (typeId && typeId >= 1 && typeId <= this.garmentTypes.length) {
            return this.garmentTypes[typeId - 1].name;
        }
        return 'Tipo no seleccionado';
    }

    // Helper to get fabric name from its ID
    getFabricName(fabricId: number): string {
        const fabric = this.fabrics.find(f => f.fabric_id == fabricId);
        return fabric ? `${fabric.fabric_name}` : 'Tela no seleccionada';
    }

    // Emits the garment data if the form is valid
    private emitGarmentsData() {
        if (this.garmentsForm.valid && this.garmentsArray.length > 0) {
            const formValue = this.garmentsForm.value;
            const garments: Garment[] = [];

            formValue.garments.forEach((garmentData: any) => {
                const garment: Garment = {
                    
                    order_id: 0,   // Placeholder, adjust if needed for actual ID
                    garment_type_id: parseInt(garmentData.garment_type_id),
                    fabric_id: parseInt(garmentData.fabric_id),
                    quantity: garmentData.quantity,
                    person_name: garmentData.person_name,
                    details: garmentData.details || '',
                    img: garmentData.img || undefined,
                    measures: garmentData.measures // Assigning measures directly
                };
                garments.push(garment);
            });

            this.garmentsDataValid.emit(garments); // Emit the array of Garment objects
        } else {
            this.garmentsDataValid.emit(null); // Emit null if the form is invalid or empty
        }
    }

    // Marks all form controls as touched to display validation errors
    markAllAsTouched() {
        this.garmentsArray.controls.forEach(control => {
            // Mark all direct controls within each garment's FormGroup as touched
            Object.keys(control.value).forEach(key => {
                control.get(key)?.markAsTouched();
            });
        });
    }

    // Checks if the overall garments form is valid
    isFormValid(): boolean {
        return this.garmentsForm.valid && this.garmentsArray.length > 0;
    }

    // Returns the garment data if the form is valid, otherwise null
    getGarmentsData(): Garment[] | null {
        if (!this.isFormValid()) {
            return null;
        }

        const formValue = this.garmentsForm.value;
        const garments: Garment[] = [];

        formValue.garments.forEach((garmentData: any) => {
            const garment: Garment = {
                garment_id: 0,
                order_id: 0,
                garment_type_id: parseInt(garmentData.garment_type_id),
                fabric_id: parseInt(garmentData.fabric_id),
                quantity: garmentData.quantity,
                person_name: garmentData.person_name,
                details: garmentData.details || '',
                img: garmentData.img || undefined,
                measures: garmentData.measures // Assigning measures directly
            };
            garments.push(garment);
        });

        return garments; // Return the array of Garment objects
    }
}